// data.ts
import { Entity } from './types';

// NOTE FOR BACKEND ARCHITECTURE:
// The `location: { city, country, lat, lng }` field is currently a frontend-only mock
// for the FABLE Global Threat Map visualization. The production backend's `Entity`
// schema, database migrations, and telemetry ingestion pipeline will need to add this
// location field to reflect physical office hub assignments and active IP geolocations.

export const INITIAL_ENTITIES: Entity[] = [
  // 1. Devraj Malhotra — The Escalated Case (#104) [Bangalore Hub]
  {
    id: 'devraj',
    name: 'Devraj Malhotra',
    role: 'Senior Staff SRE',
    department: 'Core Infrastructure',
    riskScore: 84,
    riskLevel: 'escalated',
    caseStatus: 'Open',
    classification: 'unexplained',
    caseId: '104',
    hasActiveCase: true,
    isSilentElevated: false,
    summary: 'Residual risk 84/100. Unexplained sensitive access detected across off-hours production DB clusters.',
    accessVector: 'Off-hours SSH Bastion & Postgres DB Shadow Export',
    lastActive: '6 mins ago',
    location: {
      city: 'Bangalore',
      country: 'India',
      lat: 12.9716,
      lng: 77.5946,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 18 },
      { time: 'T-5d', score: 22 },
      { time: 'T-4d', score: 25 },
      { time: 'T-3d', score: 48 },
      { time: 'T-2d', score: 62 },
      { time: 'T-1d', score: 79 },
      { time: 'Now', score: 84 },
    ],
  },

  // 2. Priya Raman — Resolved Case (#098) [London Hub]
  {
    id: 'priya',
    name: 'Priya Raman',
    role: 'Principal Data Engineer',
    department: 'Data & Analytics',
    riskScore: 24,
    riskLevel: 'resolved',
    caseStatus: 'Cleared',
    classification: 'explained',
    caseId: '098',
    hasActiveCase: true,
    isSilentElevated: false,
    summary: 'High-volume data migration validated against approved RFC-4029. Case reviewed and cleared.',
    accessVector: 'Bulk S3 Lakehouse Extract (Authorized via RFC-4029)',
    lastActive: '2 hours ago',
    location: {
      city: 'London',
      country: 'United Kingdom',
      lat: 51.5074,
      lng: -0.1278,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 15 },
      { time: 'T-5d', score: 32 },
      { time: 'T-4d', score: 76 },
      { time: 'T-3d', score: 81 },
      { time: 'T-2d', score: 55 },
      { time: 'T-1d', score: 30 },
      { time: 'Now', score: 24 },
    ],
  },

  // 3. Arjun Chen — Partially Explained / Under Review Case (#102) [San Francisco Hub]
  {
    id: 'arjun',
    name: 'Arjun Chen',
    role: 'Staff ML Systems Engineer',
    department: 'Data & Analytics',
    riskScore: 61,
    riskLevel: 'elevated',
    caseStatus: 'Reviewing',
    classification: 'partial',
    caseId: '102',
    hasActiveCase: true,
    isSilentElevated: false,
    summary: 'Model checkpoint exfiltration pattern partially correlated with scheduled benchmark run. Contextualized review pending.',
    accessVector: 'Weights & Biases Artifact Sync deviation',
    lastActive: '45 mins ago',
    location: {
      city: 'San Francisco',
      country: 'United States',
      lat: 37.7749,
      lng: -122.4194,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 20 },
      { time: 'T-5d', score: 28 },
      { time: 'T-4d', score: 35 },
      { time: 'T-3d', score: 58 },
      { time: 'T-2d', score: 64 },
      { time: 'T-1d', score: 63 },
      { time: 'Now', score: 61 },
    ],
  },

  // 4. Marcus Vance — Case #109: Autonomous System Reopen (ADDITION 3) [London Hub]
  {
    id: 'marcus-vance',
    name: 'Marcus Vance',
    role: 'DevOps Lead',
    department: 'Core Infrastructure',
    riskScore: 68,
    riskLevel: 'elevated',
    caseStatus: 'Reopened',
    classification: 'partial',
    caseId: '109',
    hasActiveCase: true,
    isSilentElevated: false,
    reopenNotice:
      'Reopened — new activity on Today, 05:22 UTC falls outside the scope of the Quarterly Maintenance RFC-388 that previously explained this case.',
    summary:
      'Autonomous Reopen: Master KMS key access at 05:22 UTC detected 82 mins after RFC-388 maintenance window closed.',
    accessVector: 'Out-of-Window Decrypt ops on core-production-kms-master',
    lastActive: '18 mins ago',
    location: {
      city: 'London',
      country: 'United Kingdom',
      lat: 51.5074,
      lng: -0.1278,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 12 },
      { time: 'T-5d', score: 14 },
      { time: 'T-4d', score: 15 },
      { time: 'T-3d', score: 22 },
      { time: 'T-2d', score: 48 },
      { time: 'T-1d', score: 53 },
      { time: 'Now', score: 68 },
    ],
  },

  // 5. Kenji Sato — Case #112: Indeterminate Classification (ADDITION 1) [Tokyo Hub]
  {
    id: 'kenji-sato',
    name: 'Kenji Sato',
    role: 'Junior Infrastructure Engineer (Day 4)',
    department: 'Core Infrastructure',
    riskScore: 34,
    riskLevel: 'calm',
    caseStatus: 'Reviewing',
    classification: 'indeterminate',
    caseId: '112',
    hasActiveCase: true,
    isSilentElevated: false,
    summary:
      'Indeterminate: Employee tenure < 7 days. Insufficient historical telemetry to establish baseline intent graph.',
    accessVector: 'Developer Git Clone & Teleport PKI Enrollment',
    lastActive: '14 mins ago',
    location: {
      city: 'Tokyo',
      country: 'Japan',
      lat: 35.6762,
      lng: 139.6503,
    },
    timelineSparkline: [
      { time: 'T-3d', score: 15 },
      { time: 'T-2d', score: 24 },
      { time: 'T-1d', score: 31 },
      { time: 'Now', score: 34 },
    ],
  },

  // Minor elevated blip 2 (Silent - never alerts, never bumps badge) [New York Hub]
  {
    id: 'elena-rostova',
    name: 'Elena Rostova',
    role: 'Financial Analyst',
    department: 'Finance & Legal',
    riskScore: 49,
    riskLevel: 'elevated',
    caseStatus: 'Reviewing',
    hasActiveCase: false,
    isSilentElevated: true,
    summary: 'Bulk payroll table read during off-cycle reconciliation window. Awaiting supervisor ledger sign-off.',
    lastActive: '3 hours ago',
    location: {
      city: 'New York',
      country: 'United States',
      lat: 40.7128,
      lng: -74.0060,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 8 },
      { time: 'T-5d', score: 10 },
      { time: 'T-4d', score: 12 },
      { time: 'T-3d', score: 15 },
      { time: 'T-2d', score: 38 },
      { time: 'T-1d', score: 51 },
      { time: 'Now', score: 49 },
    ],
  },

  // Minor elevated blip 3 (Silent - never alerts, never bumps badge) [Singapore Hub]
  {
    id: 'samira-khan',
    name: 'Samira Khan',
    role: 'Security Analyst II',
    department: 'Security Ops',
    riskScore: 47,
    riskLevel: 'elevated',
    caseStatus: 'Reviewing',
    hasActiveCase: false,
    isSilentElevated: true,
    summary: 'Synthetic honeytoken trigger tripped during simulated penetration suite. Passive monitoring active.',
    lastActive: '1 hour ago',
    location: {
      city: 'Singapore',
      country: 'Singapore',
      lat: 1.3521,
      lng: 103.8198,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 16 },
      { time: 'T-5d', score: 18 },
      { time: 'T-4d', score: 15 },
      { time: 'T-3d', score: 24 },
      { time: 'T-2d', score: 42 },
      { time: 'T-1d', score: 46 },
      { time: 'Now', score: 47 },
    ],
  },

  // 14-15 Calm Entities (Default quiet baseline state)
  {
    id: 'tomas-lindqvist',
    name: 'Tomas Lindqvist',
    role: 'Site Reliability Engineer',
    department: 'Core Infrastructure',
    riskScore: 12,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Standard Kubernetes cluster deployments and routine pod health checks.',
    lastActive: '12 mins ago',
    location: {
      city: 'Berlin',
      country: 'Germany',
      lat: 52.5200,
      lng: 13.4050,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 10 },
      { time: 'T-5d', score: 12 },
      { time: 'T-4d', score: 11 },
      { time: 'T-3d', score: 13 },
      { time: 'T-2d', score: 12 },
      { time: 'T-1d', score: 11 },
      { time: 'Now', score: 12 },
    ],
  },
  {
    id: 'maya-patel',
    name: 'Maya Patel',
    role: 'Frontend Architect',
    department: 'Frontend',
    riskScore: 8,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Design system component library updates and CDN build validation.',
    lastActive: '25 mins ago',
    location: {
      city: 'San Francisco',
      country: 'United States',
      lat: 37.7749,
      lng: -122.4194,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 6 },
      { time: 'T-5d', score: 9 },
      { time: 'T-4d', score: 8 },
      { time: 'T-3d', score: 7 },
      { time: 'T-2d', score: 8 },
      { time: 'T-1d', score: 8 },
      { time: 'Now', score: 8 },
    ],
  },
  {
    id: 'lucas-silva',
    name: 'Lucas Silva',
    role: 'Product Manager',
    department: 'Product',
    riskScore: 14,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Jira roadmapping and customer telemetry dashboard review.',
    lastActive: '40 mins ago',
    location: {
      city: 'Sydney',
      country: 'Australia',
      lat: -33.8688,
      lng: 151.2093,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 10 },
      { time: 'T-5d', score: 11 },
      { time: 'T-4d', score: 15 },
      { time: 'T-3d', score: 12 },
      { time: 'T-2d', score: 14 },
      { time: 'T-1d', score: 13 },
      { time: 'Now', score: 14 },
    ],
  },
  {
    id: 'chloe-dupont',
    name: 'Chloé Dupont',
    role: 'Security Operations Engineer',
    department: 'Security Ops',
    riskScore: 19,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Firewall log ingestion pipeline verification and alert triage.',
    lastActive: '5 mins ago',
    location: {
      city: 'Stockholm',
      country: 'Sweden',
      lat: 59.3293,
      lng: 18.0686,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 14 },
      { time: 'T-5d', score: 16 },
      { time: 'T-4d', score: 18 },
      { time: 'T-3d', score: 15 },
      { time: 'T-2d', score: 17 },
      { time: 'T-1d', score: 18 },
      { time: 'Now', score: 19 },
    ],
  },
  {
    id: 'aiden-brooks',
    name: 'Aiden Brooks',
    role: 'Senior Backend Engineer',
    department: 'Core Infrastructure',
    riskScore: 11,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'gRPC service layer refactor and unit testing pass.',
    lastActive: '1 hour ago',
    location: {
      city: 'London',
      country: 'United Kingdom',
      lat: 51.5074,
      lng: -0.1278,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 9 },
      { time: 'T-5d', score: 10 },
      { time: 'T-4d', score: 11 },
      { time: 'T-3d', score: 12 },
      { time: 'T-2d', score: 10 },
      { time: 'T-1d', score: 11 },
      { time: 'Now', score: 11 },
    ],
  },
  {
    id: 'sofia-alvarez',
    name: 'Sofia Alvarez',
    role: 'Compliance & Audit Specialist',
    department: 'Finance & Legal',
    riskScore: 15,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'SOC-2 evidence collection and auditor view policy review.',
    lastActive: '2 hours ago',
    location: {
      city: 'New York',
      country: 'United States',
      lat: 40.7128,
      lng: -74.0060,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 12 },
      { time: 'T-5d', score: 14 },
      { time: 'T-4d', score: 13 },
      { time: 'T-3d', score: 16 },
      { time: 'T-2d', score: 15 },
      { time: 'T-1d', score: 14 },
      { time: 'Now', score: 15 },
    ],
  },
  {
    id: 'wei-ming-tan',
    name: 'Wei-Ming Tan',
    role: 'Database Administrator',
    department: 'Core Infrastructure',
    riskScore: 21,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Routine index vacuuming and read-replica rebalancing.',
    lastActive: '50 mins ago',
    location: {
      city: 'Singapore',
      country: 'Singapore',
      lat: 1.3521,
      lng: 103.8198,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 18 },
      { time: 'T-5d', score: 19 },
      { time: 'T-4d', score: 20 },
      { time: 'T-3d', score: 22 },
      { time: 'T-2d', score: 21 },
      { time: 'T-1d', score: 20 },
      { time: 'Now', score: 21 },
    ],
  },
  {
    id: 'zoe-washington',
    name: 'Zoe Washington',
    role: 'UI/UX Designer',
    department: 'Product',
    riskScore: 6,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Figma component tokens export and usability prototype reviews.',
    lastActive: '30 mins ago',
    location: {
      city: 'New York',
      country: 'United States',
      lat: 40.7128,
      lng: -74.0060,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 5 },
      { time: 'T-5d', score: 6 },
      { time: 'T-4d', score: 6 },
      { time: 'T-3d', score: 5 },
      { time: 'T-2d', score: 7 },
      { time: 'T-1d', score: 6 },
      { time: 'Now', score: 6 },
    ],
  },
  {
    id: 'vikram-sharma',
    name: 'Vikram Sharma',
    role: 'Data Platform Engineer',
    department: 'Data & Analytics',
    riskScore: 16,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Airflow DAG schedule synchronization and Snowflake cost monitoring.',
    lastActive: '15 mins ago',
    location: {
      city: 'Bangalore',
      country: 'India',
      lat: 12.9716,
      lng: 77.5946,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 14 },
      { time: 'T-5d', score: 15 },
      { time: 'T-4d', score: 17 },
      { time: 'T-3d', score: 16 },
      { time: 'T-2d', score: 15 },
      { time: 'T-1d', score: 16 },
      { time: 'Now', score: 16 },
    ],
  },
  {
    id: 'hanna-becker',
    name: 'Hanna Becker',
    role: 'Legal Counsel',
    department: 'Finance & Legal',
    riskScore: 10,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Vendor NDA reviews and terms of service redactions.',
    lastActive: '4 hours ago',
    location: {
      city: 'Berlin',
      country: 'Germany',
      lat: 52.5200,
      lng: 13.4050,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 9 },
      { time: 'T-5d', score: 8 },
      { time: 'T-4d', score: 11 },
      { time: 'T-3d', score: 10 },
      { time: 'T-2d', score: 9 },
      { time: 'T-1d', score: 10 },
      { time: 'Now', score: 10 },
    ],
  },
  {
    id: 'daniel-kim',
    name: 'Daniel Kim',
    role: 'Full-Stack Engineer',
    department: 'Frontend',
    riskScore: 13,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Next.js server action instrumentation and GraphQL queries.',
    lastActive: '35 mins ago',
    location: {
      city: 'San Francisco',
      country: 'United States',
      lat: 37.7749,
      lng: -122.4194,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 11 },
      { time: 'T-5d', score: 12 },
      { time: 'T-4d', score: 14 },
      { time: 'T-3d', score: 13 },
      { time: 'T-2d', score: 12 },
      { time: 'T-1d', score: 13 },
      { time: 'Now', score: 13 },
    ],
  },
  {
    id: 'rachel-greenberg',
    name: 'Rachel Greenberg',
    role: 'SecOps Incident Responder',
    department: 'Security Ops',
    riskScore: 17,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Scheduled rotation of canary API tokens and vulnerability scan reports.',
    lastActive: '10 mins ago',
    location: {
      city: 'Stockholm',
      country: 'Sweden',
      lat: 59.3293,
      lng: 18.0686,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 15 },
      { time: 'T-5d', score: 16 },
      { time: 'T-4d', score: 15 },
      { time: 'T-3d', score: 17 },
      { time: 'T-2d', score: 18 },
      { time: 'T-1d', score: 17 },
      { time: 'Now', score: 17 },
    ],
  },
  {
    id: 'tariq-mansoor',
    name: 'Tariq Mansoor',
    role: 'ML Ops Engineer',
    department: 'Data & Analytics',
    riskScore: 18,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Triton inference server load balancing and GPU telemetry telemetry.',
    lastActive: '55 mins ago',
    location: {
      city: 'Bangalore',
      country: 'India',
      lat: 12.9716,
      lng: 77.5946,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 14 },
      { time: 'T-5d', score: 17 },
      { time: 'T-4d', score: 16 },
      { time: 'T-3d', score: 19 },
      { time: 'T-2d', score: 18 },
      { time: 'T-1d', score: 17 },
      { time: 'Now', score: 18 },
    ],
  },
  {
    id: 'olivia-tate',
    name: 'Olivia Tate',
    role: 'Technical Writer',
    department: 'Product',
    riskScore: 7,
    riskLevel: 'calm',
    hasActiveCase: false,
    summary: 'Internal engineering handbook updates and public changelog publishing.',
    lastActive: '1 hour ago',
    location: {
      city: 'Sydney',
      country: 'Australia',
      lat: -33.8688,
      lng: 151.2093,
    },
    timelineSparkline: [
      { time: 'T-6d', score: 5 },
      { time: 'T-5d', score: 6 },
      { time: 'T-4d', score: 7 },
      { time: 'T-3d', score: 6 },
      { time: 'T-2d', score: 8 },
      { time: 'T-1d', score: 7 },
      { time: 'Now', score: 7 },
    ],
  },
];
